repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    files: +php$
    hooks:
    -   id: check-yaml
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.0
    hooks:
    -   id: clang-format