repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    files: +php$
    hooks:
    -   id: check-yaml
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.4
    hooks:
    -   id: clang-format
-   repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
    -   id: clang-tidy
