name: Linux testing

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  Run_Docker_ubuntu_20-04:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check folder after git clone
        run : ls
      - name: Run Docker
        run : |
          cd docker/linux
          docker build -t "feeralbee_test" .
          docker run --privileged -v `cd ../..; pwd -P`:/feeralbeetest "feeralbee_test"
          # echo "Create folder for compile CMake"
          # mkdir build
          # ls
          # echo "Compile CMake"
          # cd build
          # cmake ../feeralbee_test
          # ls
          # echo "Build project"
          # cmake --build .
          # ls
          # echo "Run tests"
          # ctest
